name: PythonSDK WS scan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  scan-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv --user
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: White Source Scan
      env:
        WS_PRODUCTNAME: sinch-backend-sdks
        WS_PROJECTNAME: sinch-python-sdk
        WS_APIKEY: ${{ secrets.WS_USERKEY }}
        WS_USERKEY: ${{ secrets.WS_USERKEY }}
      run: |
        echo Downloading WS agent
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
          echo "Integrity Check Failed"
        else
          java -jar wss-unified-agent.jar -c wss.config -appPath requirements.txt -d .
        fi
